In [2]:
from keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img
import os
import keras
import tensorflow as tf
from tensorflow import io
import imageio
import numpy as np
import matplotlib.pyplot as plt
import cv2
from sklearn.model_selection import train_test_split
from keras import utils as np_utils

In [ ]:
#2

In [3]:
datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.15,
    height_shift_range=0.15,
    zoom_range=0.15,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')
dirs = os.listdir("handsteep")
print(len(dirs))
for filename in dirs:
    img = load_img("handsteep//{}".format(filename))
    x = img_to_array(img)
    # print(x.shape)
    x = x.reshape((1,) + x.shape) 
    # print(x.shape)
    datagen.fit(x)
    prefix = filename.split('.')[0]
    print(prefix)
    counter = 0
    for batch in datagen.flow(x, batch_size=4 , save_to_dir='dataset//handsteepg', save_prefix=prefix, save_format='jpg'):
        counter += 1
        if counter > 31:
            break  

304
001
002
003
004
005
006
007
008
009
010
011
012
013
014
015
016
017
018
019
020
021
022
023
024
025
026
027
028
029
030
031
032
033
034
035
036
037
038
039
040
041
042
043
044
045
046
047
048
049
050
051
052
053
054
055
056
057
058
059
060
061
062
063
064
065
066
067
068
069
070
071
072
073
074
075
076
077
078
079
080
081
082
083
084
085
086
087
088
089
090
091
092
093
094
095
096
097
098
099
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
130
131
132
133
134
135
136
137
138
140
141
142
143
144
145
146
147
148
149
150
151
152
153
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
IMG_4108
IMG_4109
IMG_4110
IMG_4111
IMG_4112
IMG_4113
IMG_4114
IMG_4115
IMG_4116
IMG_4117
IMG_4118
IMG_4119
IMG_4120
IMG_4121
IMG_4122
IMG_4123
IMG_4124
IMG_4125
IMG_4126
IMG_4127
IMG_4128
IMG_4129
IMG_4130
IMG_4131
IMG_4132
IMG_4133
IMG_4134
IMG_4135
IMG_4136
IMG_4137
IM

In [4]:
datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.15,
    height_shift_range=0.15,
    zoom_range=0.15,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')
dirs = os.listdir("modisteep")
print(len(dirs))
for filename in dirs:
    img = load_img("modisteep//{}".format(filename))
    x = img_to_array(img)
    # print(x.shape)
    x = x.reshape((1,) + x.shape)
    # print(x.shape)
    datagen.fit(x)
    prefix = filename.split('.')[0]
    print(prefix)
    counter = 0
    for batch in datagen.flow(x, batch_size=4 , save_to_dir='dataset//modisteepg', save_prefix=prefix, save_format='jpg'):
        counter += 1
        if counter > 23:
            break  

423
IMG_4886
IMG_4887
IMG_4888
IMG_4889
IMG_4890
IMG_4891
IMG_4892
IMG_4893
IMG_4894
IMG_4895
IMG_4896
IMG_4897
IMG_4898
IMG_4899
IMG_4900
IMG_4901
IMG_4902
IMG_4903
IMG_4904
IMG_4905
IMG_4906
IMG_4907
IMG_4908
IMG_4909
IMG_4910
IMG_4911
IMG_4912
IMG_4913
IMG_4914
IMG_4915
IMG_4916
IMG_4917
IMG_4918
IMG_4919
IMG_4920
IMG_4921
IMG_4922
IMG_4923
IMG_4924
IMG_4925
IMG_4926
IMG_4927
IMG_4928
IMG_4929
IMG_4930
IMG_4931
IMG_4932
IMG_4933
IMG_4934
IMG_4935
IMG_4936
IMG_4937
IMG_4938
IMG_4939
IMG_4940
IMG_4941
IMG_4942
IMG_4943
IMG_4944
IMG_4945
IMG_4946
IMG_4947
IMG_4948
IMG_4949
IMG_4950
IMG_4951
IMG_4952
IMG_4953
IMG_4954
IMG_4955
IMG_4956
IMG_4957
IMG_4958
IMG_4959
IMG_4960
IMG_4961
IMG_4962
IMG_4963
IMG_4964
IMG_4965
IMG_4966
IMG_4967
IMG_4968
IMG_4969
IMG_4970
IMG_4971
IMG_4972
IMG_4973
IMG_4974
IMG_4975
IMG_4976
IMG_4977
IMG_4978
IMG_4979
IMG_4980
IMG_4981
IMG_4982
IMG_4983
IMG_4984
IMG_4985
IMG_4986
IMG_4987
IMG_4988
IMG_4989
IMG_4990
IMG_4991
IMG_4992
IMG_4993
IMG_4994
IMG_4995
IMG_49

In [5]:
datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.15,
    height_shift_range=0.15,
    zoom_range=0.15,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')
dirs = os.listdir("point")
print(len(dirs))
for filename in dirs:
    img = load_img("point//{}".format(filename))
    x = img_to_array(img)
    # print(x.shape)
    x = x.reshape((1,) + x.shape) 
    # print(x.shape)
    datagen.fit(x)
    prefix = filename.split('.')[0]
    print(prefix)
    counter = 0
    for batch in datagen.flow(x, batch_size=4 , save_to_dir='dataset//pointg', save_prefix=prefix, save_format='jpg'):
        counter += 1
        if counter > 20:
            break  

372
001
002
003
004
005
006
007
008
009
010
011
012
013
014
015
016
017
018
019
020
021
022
023
024
025
026
027
028
029
030
031
032
033
034
035
036
037
038
039
040
041
042
043
044
045
046
047
048
049
050
051
052
053
1 (1)
1 (10)
1 (11)
1 (12)
1 (13)
1 (14)
1 (15)
1 (16)
1 (17)
1 (18)
1 (19)
1 (2)
1 (20)
1 (21)
1 (22)
1 (23)
1 (24)
1 (25)
1 (26)
1 (27)
1 (28)
1 (29)
1 (3)
1 (30)
1 (4)
1 (5)
1 (6)
1 (7)
1 (8)
1 (9)
IMG_4380
IMG_4381
IMG_4382
IMG_4383
IMG_4384
IMG_4385
IMG_4386
IMG_4387
IMG_4388
IMG_4389
IMG_4390
IMG_4391
IMG_4392
IMG_4393
IMG_4394
IMG_4395
IMG_4396
IMG_4397
IMG_4398
IMG_4399
IMG_4400
IMG_4401
IMG_4402
IMG_4403
IMG_4404
IMG_4405
IMG_4406
IMG_4407
IMG_4408
IMG_4409
IMG_4410
IMG_4411
IMG_4412
IMG_4413
IMG_4414
IMG_4415
IMG_4416
IMG_4417
IMG_4418
IMG_4419
IMG_4420
IMG_4421
IMG_4422
IMG_4423
IMG_4424
IMG_4425
IMG_4426
IMG_4427
IMG_4428
IMG_4429
IMG_4430
IMG_4431
IMG_4432
IMG_4433
IMG_4434
IMG_4435
IMG_4436
IMG_4437
IMG_4438
IMG_4439
IMG_4440
IMG_4441
IMG_4442
IMG_4443
IMG_444

In [6]:
datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.15,
    height_shift_range=0.15,
    zoom_range=0.15,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')
dirs = os.listdir("neg")
print(len(dirs))
for filename in dirs:
    img = load_img("neg//{}".format(filename))
    x = img_to_array(img)
    # print(x.shape)
    x = x.reshape((1,) + x.shape) 
    # print(x.shape)
    datagen.fit(x)
    prefix = filename.split('.')[0]
    print(prefix)
    counter = 0
    for batch in datagen.flow(x, batch_size=4 , save_to_dir='dataset//negg', save_prefix=prefix, save_format='jpg'):
        counter += 1
        if counter > 26:
            break  

480
0 (1)
0 (10)
0 (11)
0 (12)
0 (13)
0 (14)
0 (15)
0 (16)
0 (17)
0 (18)
0 (19)
0 (2)
0 (20)
0 (21)
0 (22)
0 (23)
0 (24)
0 (25)
0 (26)
0 (27)
0 (28)
0 (29)
0 (3)
0 (30)
0 (4)
0 (5)
0 (6)
0 (7)
0 (8)
0 (9)
1 (1)
1 (10)
1 (11)
1 (12)
1 (13)
1 (14)
1 (15)
1 (16)
1 (17)
1 (18)
1 (19)
1 (2)
1 (20)
1 (21)
1 (22)
1 (23)
1 (24)
1 (25)
1 (26)
1 (27)
1 (28)
1 (29)
1 (3)
1 (30)
1 (4)
1 (5)
1 (6)
1 (7)
1 (8)
1 (9)
11 (1)
11 (10)
11 (11)
11 (12)
11 (13)
11 (14)
11 (15)
11 (16)
11 (17)
11 (18)
11 (19)
11 (2)
11 (20)
11 (21)
11 (22)
11 (23)
11 (24)
11 (25)
11 (26)
11 (27)
11 (28)
11 (29)
11 (3)
11 (30)
11 (4)
11 (5)
11 (6)
11 (7)
11 (8)
11 (9)
2 (1)
2 (10)
2 (11)
2 (12)
2 (13)
2 (14)
2 (15)
2 (16)
2 (17)
2 (18)
2 (19)
2 (2)
2 (20)
2 (21)
2 (22)
2 (23)
2 (24)
2 (25)
2 (26)
2 (27)
2 (28)
2 (29)
2 (3)
2 (30)
2 (4)
2 (5)
2 (6)
2 (7)
2 (8)
2 (9)
21 (1)
21 (10)
21 (11)
21 (12)
21 (13)
21 (14)
21 (15)
21 (16)
21 (17)
21 (18)
21 (19)
21 (2)
21 (20)
21 (21)
21 (22)
21 (23)
21 (24)
21 (25)
21 (26)
21 (27)
21 (

In [ ]:
#3

In [7]:
dirs = os.listdir("dataset//handsteepg")
for filename in dirs:
    I = cv2.imread("dataset//handsteepg//{}".format(filename))
    image_small = cv2.resize(I, (120, 160))
    cv2.imwrite("dataset//handsteepg//{}".format(filename),image_small)

In [8]:
dirs = os.listdir("dataset//modisteepg")
for filename in dirs:
    I = cv2.imread("dataset//modisteepg//{}".format(filename))
    image_small = cv2.resize(I, (120, 160))
    cv2.imwrite("dataset//modisteepg//{}".format(filename),image_small)

In [9]:
dirs = os.listdir("dataset//pointg")
for filename in dirs:
    I = cv2.imread("dataset//pointg//{}".format(filename))
    image_small = cv2.resize(I, (120, 160))
    cv2.imwrite("dataset//pointg//{}".format(filename),image_small)

In [10]:
dirs = os.listdir("dataset//negg")
for filename in dirs:
    I = cv2.imread("dataset//negg//{}".format(filename))
    image_small = cv2.resize(I, (120, 160))
    cv2.imwrite("dataset//negg//{}".format(filename),image_small)

In [11]:
def read(dataset_dir):
    Y_label=[]
    X_data=[]
    for fileholder in os.listdir(dataset_dir):
        loc= os.path.join(dataset_dir,fileholder)
        for file in os.listdir(loc):
            image=os.path.join(loc,file)
            img=cv2.imread(image)
            X_data.append(img)
            if(fileholder=='handsteepg'):
                Y_label.append(0)
            elif(fileholder=='modisteepg'):
                Y_label.append(1)
            elif(fileholder=='pointg'):
                Y_label.append(2)
            elif(fileholder=='negg'):
                Y_label.append(3)
    X_data=np.array(X_data)
    Y_label=np.array(Y_label)
    Y_label = np_utils.to_categorical(Y_label, num_classes=4)
    return X_data,Y_label

f="dataset"
X_data,Y_label=read(f)
print(X_data.shape)

(40596, 160, 120, 3)


In [ ]:
#5

In [12]:
from keras import layers
from keras.models import Sequential
from keras import models
from keras import optimizers
from keras.optimizers import adam
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [ ]:

np.random.seed(100)
np.random.shuffle(X_data) 
np.random.seed(100)
np.random.shuffle(Y_label)
 
np.random.seed(200)
np.random.shuffle(test_data) 
np.random.seed(200)
np.random.shuffle(test_label)

In [14]:
#LeNet

model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(160, 120, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten()) 
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

history = model.fit(X_data, Y_label, batch_size=32, epochs=10,validation_split=0.1)

Train on 36536 samples, validate on 4060 samples
Epoch 1/10
36536/36536 [==============================] - 442s 12ms/step - loss: 8.4069 - accuracy: 0.7883 - val_loss: 2.0079 - val_accuracy: 0.2833
Epoch 2/10
36536/36536 [==============================] - 440s 12ms/step - loss: 0.3688 - accuracy: 0.8893 - val_loss: 0.9944 - val_accuracy: 0.6190
Epoch 3/10
36536/36536 [==============================] - 441s 12ms/step - loss: 0.2976 - accuracy: 0.9151 - val_loss: 1.6810 - val_accuracy: 0.2628
Epoch 4/10
36536/36536 [==============================] - 446s 12ms/step - loss: 0.2455 - accuracy: 0.9290 - val_loss: 0.6389 - val_accuracy: 0.7941
Epoch 5/10
36536/36536 [==============================] - 447s 12ms/step - loss: 0.2292 - accuracy: 0.9307 - val_loss: 1.8015 - val_accuracy: 0.4554
Epoch 6/10
36536/36536 [==============================] - 455s 12ms/step - loss: 0.2088 - accuracy: 0.9377 - val_loss: 2.5949 - val_accuracy: 0.3544
Epoch 7/10
36536/36536 [==============================] -

In [ ]:
# AlexNet

model = Sequential()
model.add(Conv2D(filters=96, kernel_size=(11,11),strides=(4,4), padding='valid',input_shape=(160,120,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding='valid'))

model.add(Conv2D(filters=256, kernel_size=(5,5), strides=(1,1), padding='same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding='valid'))

model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding='valid'))

model.add(Flatten())
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
 
model.add(Dense(4096, activation='relu'))
model.add(Dropout(0.5))
 
model.add(Dense(1000, activation='relu'))
model.add(Dropout(0.5))
 
# Output Layer
model.add(Dense(4))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])


history = model.fit(X_data, Y_label, batch_size=32, epochs=10,validation_split=0.1)

In [17]:
#6

In [15]:
model.save('model3.h5')

In [3]:
#above is training model

In [ ]:
#7

In [3]:
model = tf.keras.models.load_model('model3.h5')

In [24]:
#test on webcam
import cv2
import numpy as np
from matplotlib import animation, rc
from PIL import Image
from keras import models
import matplotlib.pyplot as plt
video = cv2.VideoCapture(0)
while True:
        testdata=[]
        _, frame = video.read()
        ir = cv2.resize(frame,(120,160))
        testdata.append(ir)
        tdata=np.array(testdata)
        tdata=tdata/255
        label=model.predict(tdata)
        print(label)      

#         plt.barh(x, label[0], align="center")
#         plt.xlabel("label")
#         plt.ylabel("probability")
#         plt.show()
        
        
        cv2.imshow("Capturing", frame)
        key=cv2.waitKey(1)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()

[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[[0.22585833 0.10512494 0.66901666]]
[

[[0.3304469  0.19797383 0.47157928]]
[[0.335445   0.20689021 0.45766488]]
[[0.3100381  0.20764922 0.48231265]]
[[0.27918682 0.19752385 0.5232894 ]]
[[0.27258754 0.16823864 0.5591738 ]]
[[0.2830927  0.18348472 0.5334226 ]]
[[0.28010502 0.18127377 0.5386212 ]]
[[0.26171947 0.17871337 0.55956715]]
[[0.2712757  0.17465755 0.5540667 ]]
[[0.26253965 0.1685297  0.56893057]]
[[0.26684168 0.15961443 0.57354397]]
[[0.29252806 0.16762093 0.53985107]]
[[0.30037677 0.16898414 0.53063905]]
[[0.27849177 0.15963185 0.56187636]]
[[0.2811186  0.16190279 0.55697864]]
[[0.28972307 0.16614886 0.54412806]]
[[0.2805732  0.17592244 0.54350436]]
[[0.2669591  0.17752686 0.55551404]]
[[0.26736847 0.17929612 0.55333537]]
[[0.26298442 0.17967588 0.55733967]]
[[0.27107802 0.1826368  0.5462852 ]]
[[0.28737506 0.1917729  0.52085197]]
[[0.31775853 0.27183592 0.41040555]]
[[0.31083754 0.27545327 0.41370928]]
[[0.29705435 0.2625447  0.44040105]]
[[0.29044616 0.25669298 0.45286086]]
[[0.2878743  0.25013712 0.46198857]]
[

[[0.24542794 0.24150491 0.5130671 ]]
[[0.24523678 0.24050485 0.5142584 ]]
[[0.24671596 0.23875609 0.514528  ]]
[[0.24710557 0.23838982 0.5145046 ]]
[[0.24822643 0.23952535 0.51224816]]
[[0.2509476  0.24072239 0.50833005]]
[[0.25040844 0.24569373 0.50389785]]
[[0.25106406 0.24587004 0.5030659 ]]
[[0.25018352 0.24848929 0.50132716]]
[[0.24823573 0.25095552 0.5008087 ]]
[[0.24833427 0.25331768 0.49834806]]
[[0.24659117 0.25096914 0.50243974]]
[[0.24726085 0.24954824 0.5031909 ]]
[[0.24835856 0.24500197 0.5066394 ]]
[[0.24843746 0.2436462  0.5079163 ]]
[[0.24552026 0.24165852 0.5128212 ]]
[[0.24519041 0.24166894 0.5131406 ]]
[[0.24520168 0.24158475 0.5132136 ]]
[[0.244565   0.2432759  0.51215905]]
[[0.24460089 0.24153902 0.51386005]]
[[0.2438328  0.24062753 0.51553977]]
[[0.2481807 0.2503465 0.5014729]]
[[0.24871854 0.2450465  0.506235  ]]
[[0.26010078 0.2539923  0.485907  ]]
[[0.26553488 0.24753502 0.4869301 ]]
[[0.2662363  0.24857995 0.48518384]]
[[0.26594898 0.24213271 0.49191824]]
[[0.

[[0.268239   0.22705723 0.50470376]]
[[0.26924953 0.23530407 0.49544632]]
[[0.26349863 0.23344879 0.5030526 ]]
[[0.26323906 0.22935797 0.507403  ]]
[[0.25248003 0.22297029 0.52454966]]
[[0.2457928  0.21849805 0.53570914]]
[[0.23608774 0.21152368 0.5523886 ]]
[[0.22923201 0.19922826 0.57153964]]
[[0.22868678 0.19951582 0.5717973 ]]
[[0.22675541 0.20145737 0.57178724]]
[[0.21898472 0.19550075 0.5855146 ]]
[[0.2188094  0.19103767 0.590153  ]]
[[0.2160046  0.18448722 0.59950817]]
[[0.2132691  0.18029766 0.6064333 ]]
[[0.21213095 0.17705388 0.6108151 ]]
[[0.21363044 0.17684345 0.6095261 ]]
[[0.21956177 0.1715372  0.608901  ]]
[[0.22552632 0.17421804 0.60025567]]
[[0.2236788  0.17402647 0.6022947 ]]
[[0.2178429  0.17070992 0.61144716]]
[[0.2180823 0.1723027 0.609615 ]]
[[0.22054599 0.1783493  0.6011047 ]]
[[0.22242355 0.17919476 0.5983816 ]]
[[0.22303063 0.17841075 0.5985586 ]]
[[0.2200949  0.17720902 0.60269606]]
[[0.22198491 0.17711233 0.6009028 ]]
[[0.2207988  0.17562807 0.60357314]]
[[0.

[[0.24681106 0.2913917  0.4617972 ]]
[[0.24749596 0.2911965  0.4613076 ]]
[[0.24795976 0.2910601  0.46098012]]
[[0.24712917 0.29020905 0.46266174]]
[[0.24684936 0.29026207 0.4628885 ]]
[[0.24680208 0.2907817  0.46241614]]
[[0.24680208 0.2907817  0.46241614]]
[[0.24645069 0.29013848 0.46341082]]
[[0.24647972 0.29036754 0.4631527 ]]
[[0.24690673 0.29019895 0.4628943 ]]
[[0.24685535 0.28963068 0.46351397]]
[[0.24708359 0.28971058 0.46320587]]
[[0.2475087  0.28941837 0.46307296]]
[[0.24710624 0.2884326  0.46446118]]
[[0.24855958 0.28818575 0.46325472]]
[[0.24902843 0.28857684 0.46239474]]
[[0.24918574 0.28782767 0.46298656]]
[[0.2486472  0.28773817 0.46361458]]
[[0.24994652 0.28736085 0.46269262]]
[[0.24914171 0.28733405 0.46352422]]
[[0.25098765 0.28423905 0.4647734 ]]
[[0.25186843 0.28267622 0.46545532]]
[[0.25137338 0.28188676 0.46673986]]
[[0.25211084 0.28057748 0.46731168]]
[[0.25294963 0.2803789  0.4666714 ]]
[[0.25399604 0.27919844 0.46680564]]
[[0.2533077  0.28030434 0.46638805]]
[

In [40]:
#test
testdata=[]
I=cv2.imread('point//IMG_4380.JPG')
ir = cv2.resize(I, (120, 160))
testdata.append(ir)
tdata=np.array(testdata)
tdata=tdata/255
y=model.predict(tdata)
print(type(y))
print(y.size)
print(y)

<class 'numpy.ndarray'>
3
[[2.0732905e-12 3.6205520e-12 1.0000000e+00]]


In [14]:
#test on video
import cv2     # for capturing videos
import math   # for mathematical operations
import matplotlib.pyplot as plt    # for plotting the images
import pandas as pd
from keras.preprocessing import image   # for preprocessing the images
import numpy as np    # for mathematical operations
from keras.utils import np_utils
from skimage.transform import resize   # for resizing images
import json


jtxt={}
jtxt[ "head up" ] = []


cap = cv2.VideoCapture("test.avi")
while True:
        testdata=[]
        tlabel=[]
        _, frame = cap.read()
        ir = cv2.resize(frame,(120,160))
        testdata.append(ir)
        tdata=np.array(testdata)
        tdata = tf.cast(tdata, tf.float32)
        label=model.predict(tdata)      
        time=cap.get(cv2.CAP_PROP_POS_MSEC)
        print( time )
        
        
#         tlabel=['Time:',time,'Label:',label[0].tolist()]
        
#         jtxt["Time"].append(time)
        jtxt["head up"].append([time, label[0].tolist()])

        
print( jtxt )
with open('timeLabel.json','w') as f:
    json.dump(jtxt,f)


0.0
933.3333333333334
1000.0
1066.6666666666667
1133.3333333333333
1200.0
1266.6666666666665
1333.3333333333333
1400.0
1466.6666666666665
1533.3333333333333
1600.0
1666.6666666666667
1733.3333333333335
1800.0
1866.6666666666667
1933.3333333333333
2000.0
2066.6666666666665
2133.3333333333335
2200.0
2266.6666666666665
2333.3333333333335
2400.0
2466.666666666667
2533.333333333333
2600.0
2666.6666666666665
2733.3333333333335
2800.0
2866.6666666666665
2933.333333333333
3000.0
3066.6666666666665
3133.3333333333335
3200.0
3266.6666666666665
3333.3333333333335
3400.0
3466.666666666667
3533.333333333333
3600.0
3666.6666666666665
3733.3333333333335
3800.0
3866.6666666666665
3933.333333333333
4000.0
4066.6666666666665
4133.333333333333
4200.0
4266.666666666667
4333.333333333333
4400.0
4466.666666666667
4533.333333333333
4600.0
4666.666666666667
4733.333333333333
4800.0
4866.666666666666
4933.333333333334
5000.0
5066.666666666666
5133.333333333333
5200.0
5266.666666666667
5333.333333333333
5400.0


error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [15]:
print( jtxt )
with open('timeLabel.json','w') as f:
    json.dump(jtxt,f)

{'head up': [[0.0, [4.179383540758863e-05, 0.9529572129249573, 0.047000765800476074, 2.2947240552184667e-07]], [933.3333333333334, [4.334282493800856e-05, 0.9509953260421753, 0.04896104335784912, 3.937243207019492e-07]], [1000.0, [3.14625576720573e-05, 0.9507606625556946, 0.04920705035328865, 7.765943337290082e-07]], [1066.6666666666667, [0.00011766576790250838, 0.948471188545227, 0.0514034777879715, 7.685373930144124e-06]], [1133.3333333333333, [1.6568497812841088e-05, 0.9644963145256042, 0.03548707440495491, 7.231864884715833e-08]], [1200.0, [0.00014341900532599539, 0.914146363735199, 0.08571004867553711, 1.7745732350249455e-07]], [1266.6666666666665, [0.00010427474626339972, 0.9041802287101746, 0.09571489691734314, 5.666367997037014e-07]], [1333.3333333333333, [7.359963638009503e-05, 0.9096068739891052, 0.09031519293785095, 4.367927431303542e-06]], [1400.0, [7.472594461432891e-06, 0.9645062685012817, 0.03548280894756317, 3.416566642044927e-06]], [1466.6666666666665, [1.9801043436018

In [13]:
d=json.load( open('timeLabel.json','r') )
d

{'Time': [0.0,
  933.3333333333334,
  1000.0,
  1066.6666666666667,
  1133.3333333333333,
  1200.0,
  1266.6666666666665,
  1333.3333333333333,
  1400.0,
  1466.6666666666665,
  1533.3333333333333,
  1600.0,
  1666.6666666666667,
  1733.3333333333335,
  1800.0,
  1866.6666666666667,
  1933.3333333333333,
  2000.0,
  2066.6666666666665,
  2133.3333333333335,
  2200.0,
  2266.6666666666665,
  2333.3333333333335,
  2400.0,
  2466.666666666667,
  2533.333333333333,
  2600.0,
  2666.6666666666665,
  2733.3333333333335,
  2800.0,
  2866.6666666666665,
  2933.333333333333,
  3000.0,
  3066.6666666666665,
  3133.3333333333335,
  3200.0,
  3266.6666666666665,
  3333.3333333333335,
  3400.0,
  3466.666666666667,
  3533.333333333333,
  3600.0,
  3666.6666666666665,
  3733.3333333333335,
  3800.0,
  3866.6666666666665,
  3933.333333333333,
  4000.0,
  4066.6666666666665,
  4133.333333333333,
  4200.0,
  4266.666666666667,
  4333.333333333333,
  4400.0,
  4466.666666666667,
  4533.333333333333,
  4